spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exemplo_logback_api
    username: postgres
    password: Sen@c2023
    driverClassName: org.postgresql.Driver
  security:
    secret: "exemplo-aula-jwt"
    expiration_time: 5